import { PrismaClient, EmploymentStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const nurses = [
    // Khoa Nội (10 nurses)
    {
      id: 'N001',
      name: 'ĐD. Nguyễn Thị Hoa',
      department: 'Khoa Nội',
      shift: 'Sáng',
      phone: '0911111111',
      email: 'hoa.nguyen@hospital.com',
      experience: 8,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N002',
      name: 'ĐD. Trần Văn Bình',
      department: 'Khoa Nội',
      shift: 'Chiều',
      phone: '0911111112',
      email: 'binh.tran@hospital.com',
      experience: 6,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N003',
      name: 'ĐD. Lê Thị Cúc',
      department: 'Khoa Nội',
      shift: 'Tối',
      phone: '0911111113',
      email: 'cuc.le@hospital.com',
      experience: 10,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N004',
      name: 'ĐD. Phạm Văn Đạt',
      department: 'Khoa Nội',
      shift: 'Sáng',
      phone: '0911111114',
      email: 'dat.pham@hospital.com',
      experience: 5,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N031',
      name: 'ĐD. Nguyễn Thị Oanh',
      department: 'Khoa Nội',
      shift: 'Chiều',
      phone: '0911111131',
      email: 'oanh.nguyen@hospital.com',
      experience: 7,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N032',
      name: 'ĐD. Trần Văn Dũng',
      department: 'Khoa Nội',
      shift: 'Tối',
      phone: '0911111132',
      email: 'dung.tran@hospital.com',
      experience: 9,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N033',
      name: 'ĐD. Lê Thị Quang',
      department: 'Khoa Nội',
      shift: 'Sáng',
      phone: '0911111133',
      email: 'quang.le@hospital.com',
      experience: 4,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N034',
      name: 'ĐD. Phạm Thị Ngọc',
      department: 'Khoa Nội',
      shift: 'Chiều',
      phone: '0911111134',
      email: 'ngoc.pham@hospital.com',
      experience: 6,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N035',
      name: 'ĐD. Vũ Văn Tài',
      department: 'Khoa Nội',
      shift: 'Tối',
      phone: '0911111135',
      email: 'tai.vu@hospital.com',
      experience: 8,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N036',
      name: 'ĐD. Đỗ Thị Hạnh',
      department: 'Khoa Nội',
      shift: 'Sáng',
      phone: '0911111136',
      email: 'hanh.do@hospital.com',
      experience: 5,
      status: EmploymentStatus.ACTIVE,
    },

    // Khoa Ngoại (8 nurses)
    {
      id: 'N005',
      name: 'ĐD. Vũ Thị Dung',
      department: 'Khoa Ngoại',
      shift: 'Sáng',
      phone: '0922222225',
      email: 'dung.vu@hospital.com',
      experience: 7,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N006',
      name: 'ĐD. Đỗ Văn Giang',
      department: 'Khoa Ngoại',
      shift: 'Chiều',
      phone: '0922222226',
      email: 'giang.do@hospital.com',
      experience: 9,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N007',
      name: 'ĐD. Nguyễn Thị Hằng',
      department: 'Khoa Ngoại',
      shift: 'Tối',
      phone: '0922222227',
      email: 'hang.nguyen@hospital.com',
      experience: 11,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N008',
      name: 'ĐD. Trần Văn Hiếu',
      department: 'Khoa Ngoại',
      shift: 'Sáng',
      phone: '0922222228',
      email: 'hieu.tran@hospital.com',
      experience: 4,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N037',
      name: 'ĐD. Lê Văn Khoa',
      department: 'Khoa Ngoại',
      shift: 'Chiều',
      phone: '0922222237',
      email: 'khoa.le@hospital.com',
      experience: 6,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N038',
      name: 'ĐD. Phạm Thị Linh',
      department: 'Khoa Ngoại',
      shift: 'Tối',
      phone: '0922222238',
      email: 'linh.pham@hospital.com',
      experience: 8,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N039',
      name: 'ĐD. Vũ Văn Minh',
      department: 'Khoa Ngoại',
      shift: 'Sáng',
      phone: '0922222239',
      email: 'minh.vu@hospital.com',
      experience: 5,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N040',
      name: 'ĐD. Đỗ Thị Uyên',
      department: 'Khoa Ngoại',
      shift: 'Chiều',
      phone: '0922222240',
      email: 'uyen.do@hospital.com',
      experience: 7,
      status: EmploymentStatus.ACTIVE,
    },

    // Khoa Tim mạch (6 nurses)
    {
      id: 'N009',
      name: 'ĐD. Lê Thị Kim',
      department: 'Khoa Tim mạch',
      shift: 'Sáng',
      phone: '0933333339',
      email: 'kim.le@hospital.com',
      experience: 6,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N010',
      name: 'ĐD. Phạm Văn Long',
      department: 'Khoa Tim mạch',
      shift: 'Chiều',
      phone: '0933333340',
      email: 'long.pham@hospital.com',
      experience: 8,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N011',
      name: 'ĐD. Vũ Thị Mai',
      department: 'Khoa Tim mạch',
      shift: 'Tối',
      phone: '0933333341',
      email: 'mai.vu@hospital.com',
      experience: 10,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N041',
      name: 'ĐD. Nguyễn Văn Nam',
      department: 'Khoa Tim mạch',
      shift: 'Sáng',
      phone: '0933333341',
      email: 'nam.nguyen@hospital.com',
      experience: 4,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N042',
      name: 'ĐD. Trần Thị Oanh',
      department: 'Khoa Tim mạch',
      shift: 'Chiều',
      phone: '0933333342',
      email: 'oanh.tran@hospital.com',
      experience: 7,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N043',
      name: 'ĐD. Lê Văn Phúc',
      department: 'Khoa Tim mạch',
      shift: 'Tối',
      phone: '0933333343',
      email: 'phuc.le@hospital.com',
      experience: 9,
      status: EmploymentStatus.ACTIVE,
    },

    // Khoa Sản (5 nurses)
    {
      id: 'N012',
      name: 'ĐD. Đỗ Thị Nga',
      department: 'Khoa Sản',
      shift: 'Sáng',
      phone: '0944444412',
      email: 'nga.do@hospital.com',
      experience: 9,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N013',
      name: 'ĐD. Nguyễn Văn Phúc',
      department: 'Khoa Sản',
      shift: 'Chiều',
      phone: '0944444413',
      email: 'phuc.nguyen@hospital.com',
      experience: 5,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N014',
      name: 'ĐD. Trần Thị Quỳnh',
      department: 'Khoa Sản',
      shift: 'Tối',
      phone: '0944444414',
      email: 'quynh.tran@hospital.com',
      experience: 12,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N044',
      name: 'ĐD. Lê Thị Thanh',
      department: 'Khoa Sản',
      shift: 'Sáng',
      phone: '0944444444',
      email: 'thanh.le@hospital.com',
      experience: 6,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N045',
      name: 'ĐD. Phạm Văn Tùng',
      department: 'Khoa Sản',
      shift: 'Chiều',
      phone: '0944444445',
      email: 'tung.pham@hospital.com',
      experience: 8,
      status: EmploymentStatus.ACTIVE,
    },

    // Khoa Nhi (4 nurses)
    {
      id: 'N015',
      name: 'ĐD. Lê Văn Sơn',
      department: 'Khoa Nhi',
      shift: 'Sáng',
      phone: '0955555515',
      email: 'son.le@hospital.com',
      experience: 7,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N016',
      name: 'ĐD. Phạm Thị Thủy',
      department: 'Khoa Nhi',
      shift: 'Chiều',
      phone: '0955555516',
      email: 'thuy.pham@hospital.com',
      experience: 4,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N046',
      name: 'ĐD. Vũ Văn Việt',
      department: 'Khoa Nhi',
      shift: 'Tối',
      phone: '0955555546',
      email: 'viet.vu@hospital.com',
      experience: 9,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N047',
      name: 'ĐD. Đỗ Thị Xuân',
      department: 'Khoa Nhi',
      shift: 'Sáng',
      phone: '0955555547',
      email: 'xuan.do@hospital.com',
      experience: 5,
      status: EmploymentStatus.ACTIVE,
    },

    // Khoa Thần kinh (3 nurses)
    {
      id: 'N018',
      name: 'ĐD. Đỗ Thị Uyên',
      department: 'Khoa Thần kinh',
      shift: 'Sáng',
      phone: '0966666618',
      email: 'uyen.do@hospital.com',
      experience: 11,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N019',
      name: 'ĐD. Nguyễn Văn Vinh',
      department: 'Khoa Thần kinh',
      shift: 'Chiều',
      phone: '0966666619',
      email: 'vinh.nguyen@hospital.com',
      experience: 8,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N048',
      name: 'ĐD. Trần Thị Yến',
      department: 'Khoa Thần kinh',
      shift: 'Tối',
      phone: '0966666648',
      email: 'yen.tran@hospital.com',
      experience: 6,
      status: EmploymentStatus.ACTIVE,
    },

    // Khoa Chấn thương chỉnh hình (3 nurses)
    {
      id: 'N021',
      name: 'ĐD. Lê Văn Yên',
      department: 'Khoa Chấn thương chỉnh hình',
      shift: 'Sáng',
      phone: '0977777721',
      email: 'yen.le@hospital.com',
      experience: 6,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N022',
      name: 'ĐD. Phạm Thị An',
      department: 'Khoa Chấn thương chỉnh hình',
      shift: 'Chiều',
      phone: '0977777722',
      email: 'an.pham@hospital.com',
      experience: 8,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N049',
      name: 'ĐD. Vũ Văn An',
      department: 'Khoa Chấn thương chỉnh hình',
      shift: 'Tối',
      phone: '0977777749',
      email: 'an.vu@hospital.com',
      experience: 7,
      status: EmploymentStatus.ACTIVE,
    },

    // Other departments (remaining 6 nurses)
    {
      id: 'N024',
      name: 'ĐD. Đỗ Thị Chi',
      department: 'Khoa Mắt',
      shift: 'Sáng',
      phone: '0988888824',
      email: 'chi.do@hospital.com',
      experience: 5,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N026',
      name: 'ĐD. Trần Thị Hạnh',
      department: 'Khoa Tai mũi họng',
      shift: 'Sáng',
      phone: '0988888826',
      email: 'hanh.tran@hospital.com',
      experience: 7,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N028',
      name: 'ĐD. Phạm Thị Liên',
      department: 'Khoa Hồi sức cấp cứu',
      shift: 'Sáng',
      phone: '0999999928',
      email: 'lien.pham@hospital.com',
      experience: 10,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N029',
      name: 'ĐD. Vũ Văn Minh',
      department: 'Khoa Hồi sức cấp cứu',
      shift: 'Chiều',
      phone: '0999999929',
      email: 'minh.vu@hospital.com',
      experience: 12,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N030',
      name: 'ĐD. Đỗ Thị Ngân',
      department: 'Khoa Hồi sức cấp cứu',
      shift: 'Tối',
      phone: '0999999930',
      email: 'ngan.do@hospital.com',
      experience: 9,
      status: EmploymentStatus.ACTIVE,
    },
    {
      id: 'N050',
      name: 'ĐD. Nguyễn Thị Bình',
      department: 'Khoa Da liễu',
      shift: 'Sáng',
      phone: '0900000050',
      email: 'binh.nguyen@hospital.com',
      experience: 4,
      status: EmploymentStatus.ACTIVE,
    },
  ];

  await prisma.nurse.createMany({
    data: nurses,
    skipDuplicates: true,
  });

  console.log(`✅ Seeded ${nurses.length} nurses`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
