-- DropForeignKey
ALTER TABLE "test_results" DROP CONSTRAINT IF EXISTS "test_results_specimen_id_fkey";

-- DropForeignKey
ALTER TABLE "test_results" DROP CONSTRAINT IF EXISTS "test_results_test_type_id_fkey";

-- DropForeignKey
ALTER TABLE "test_types" DROP CONSTRAINT IF EXISTS "test_types_categoryId_fkey";

-- AlterTable: test_categories
ALTER TABLE "test_categories" DROP CONSTRAINT IF EXISTS "test_categories_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ADD CONSTRAINT "test_categories_pkey" PRIMARY KEY ("id");

-- AlterTable: test_results
ALTER TABLE "test_results" DROP CONSTRAINT IF EXISTS "test_results_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "test_type_id" SET DATA TYPE INTEGER,
ALTER COLUMN "specimen_id" SET DATA TYPE INTEGER,
ADD CONSTRAINT "test_results_pkey" PRIMARY KEY ("id");

-- AlterTable: test_specimens
ALTER TABLE "test_specimens" DROP CONSTRAINT IF EXISTS "test_specimens_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ADD CONSTRAINT "test_specimens_pkey" PRIMARY KEY ("id");

-- AlterTable: test_types
ALTER TABLE "test_types" DROP CONSTRAINT IF EXISTS "test_types_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "categoryId" SET DATA TYPE INTEGER,
ADD CONSTRAINT "test_types_pkey" PRIMARY KEY ("id");

-- AddForeignKey
ALTER TABLE "test_types" 
  ADD CONSTRAINT "test_types_categoryId_fkey" 
  FOREIGN KEY ("categoryId") REFERENCES "test_categories"("id") 
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "test_results" 
  ADD CONSTRAINT "test_results_test_type_id_fkey" 
  FOREIGN KEY ("test_type_id") REFERENCES "test_types"("id") 
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "test_results" 
  ADD CONSTRAINT "test_results_specimen_id_fkey" 
  FOREIGN KEY ("specimen_id") REFERENCES "test_specimens"("id") 
  ON DELETE SET NULL ON UPDATE CASCADE;
